# Generated by Django 2.2 on 2019-05-08 10:01

import Appis.posts.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=Appis.posts.models.upload, verbose_name='宣传图片')),
                ('flag', models.CharField(default='blog', max_length=30, verbose_name='图片功能标识')),
                ('title', models.CharField(default='', max_length=120, verbose_name='宣传标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='内容讯息')),
                ('status', models.BooleanField(default=True, verbose_name='是否可用')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '活动讯息',
                'verbose_name_plural': '活动讯息',
            },
        ),
    ]
