# Generated by Django 2.2 on 2019-05-05 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190430_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.UUID('400b24e2-6f17-11e9-bc92-acde48001122'), editable=False, primary_key=True, serialize=False),
        ),
    ]
