# Generated by Django 2.2 on 2019-05-05 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190505_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5fc2dacc-6f18-11e9-9dde-acde48001122'), editable=False, primary_key=True, serialize=False),
        ),
    ]
