# Generated by Django 2.2 on 2019-05-05 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190505_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ffb4c152-6f19-11e9-b1cc-acde48001122'), editable=False, primary_key=True, serialize=False),
        ),
    ]
