# Generated by Django 2.2 on 2019-05-05 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20190505_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f21469e-6f1c-11e9-b726-acde48001122'), editable=False, primary_key=True, serialize=False),
        ),
    ]
