# Generated by Django 2.2 on 2019-05-05 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20190505_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.UUID('360e09c6-6f1e-11e9-bcf3-acde48001122'), editable=False, primary_key=True, serialize=False),
        ),
    ]
