# Generated by Django 2.2 on 2019-05-05 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20190505_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea65e60a-6f1e-11e9-b534-acde48001122'), editable=False, primary_key=True, serialize=False),
        ),
    ]
