# Generated by Django 2.2 on 2019-05-08 10:01

import Extra.utils.union
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, default=Extra.utils.union.order_number, max_length=50, null=True, verbose_name='编号')),
                ('order_title', models.CharField(blank=True, default='', max_length=50, verbose_name='标题')),
                ('order_content', models.CharField(blank=True, max_length=240, null=True, verbose_name='内容')),
                ('order_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='预约日期')),
                ('order_time', models.CharField(blank=True, max_length=8, null=True, verbose_name='预约时间')),
                ('order_status', models.IntegerField(choices=[(0, '已过期'), (1, '待回应'), (2, '预约中'), (3, '已完成')], default=1, verbose_name='订单状态')),
                ('status', models.BooleanField(default=True, verbose_name='是否可用')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderBelong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='是否可用')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('member_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.MemberMsg', verbose_name='订单所属用户')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单所属记录',
                'verbose_name_plural': '订单所属记录',
            },
        ),
    ]
